name: Lint files

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Lint with prettier
        run: |
          npx prettier --check .

      - name: Lint with ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx
